version: '3.3'

services:
  ig-obsessed-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ig-obsessed-backend-dev
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=development
      - PORT=7001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - ig-obsessed-dev-network
    command: npm run dev

networks:
  ig-obsessed-dev-network:
    driver: bridge