version: '3.3'

services:
  ig-obsessed-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ig-obsessed-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ig-obsessed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ig-obsessed-network:
    driver: bridge

# Optional: If you want to add a reverse proxy later
# nginx:
#   image: nginx:alpine
#   container_name: ig-obsessed-nginx
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   depends_on:
#     - ig-obsessed-backend
#   networks:
#     - ig-obsessed-ne